# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  zsh-async = {
    pname = "zsh-async";
    version = "v1.8.6";
    src = fetchFromGitHub {
      owner = "mafredri";
      repo = "zsh-async";
      rev = "v1.8.6";
      fetchSubmodules = false;
      sha256 = "sha256-Js/9vGGAEqcPmQSsumzLfkfwljaFWHJ9sMWOgWDi0NI=";
    };
  };
  zsh-history-substring-search = {
    pname = "zsh-history-substring-search";
    version = "v1.1.0";
    src = fetchFromGitHub {
      owner = "zsh-users";
      repo = "zsh-history-substring-search";
      rev = "v1.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-GSEvgvgWi1rrsgikTzDXokHTROoyPRlU0FVpAoEmXG4=";
    };
  };
  zsh-syntax-highlighting = {
    pname = "zsh-syntax-highlighting";
    version = "0.8.0";
    src = fetchFromGitHub {
      owner = "zsh-users";
      repo = "zsh-syntax-highlighting";
      rev = "0.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-iJdWopZwHpSyYl5/FQXEW7gl/SrKaYDEtTH9cGP7iPo=";
    };
  };
}
